# arxivの学問領域の指定
subject: 'cat:quant-ph'

# 検索キーワード
keywords:
        grover: 5
        noise: 1
        entanglment: 1
        entropy: 1
        algorithm: 1
        multipartite: 1
        quantum: 1
        mutual: 1

# 通知の閾値
score_threshold: 5
